import random
import numpy as np
nulo = 0.3
bajo = 0.8
medio = 0.88
alto = 0.9
# Definir habilidades y sus pesos por posición
stats_weights = {
    "GK": {
        "Attack": nulo,
        "Defence": alto,
        "Header Accuracy": bajo,
        "Dribble Accuracy": 0.6,
        "Short Pass Accuracy": nulo,
        "Short Pass Speed": nulo,
        "Long Pass Accuracy": nulo,
        "Long Pass Speed": nulo,
        "Shot Accuracy": nulo,
        "Place Kicking": nulo,
        "Swerve": nulo,
        "Ball Controll": nulo,
        "Goal Keeping Skills": alto,
        "Response": medio,
        "Explosive Power": 0.4,
        "Dribble Speed": nulo,
        "Top Speed": 0.5,
        "Body Balance": alto,
        "Stamina": nulo,
        "Kicking Power": nulo,
        "Jump": alto,
        "Tenacity": 0.6,
        "Teamwork": 0.6,
    },
    "SWP": {
        "Attack": bajo,
        "Defence": alto,
        "Header Accuracy": medio,
        "Dribble Accuracy": bajo,
        "Short Pass Accuracy": medio,
        "Short Pass Speed": bajo,
        "Long Pass Accuracy": medio,
        "Long Pass Speed": bajo,
        "Shot Accuracy": 0.5,
        "Place Kicking": 0.6,
        "Swerve": 0.6,
        "Ball Controll": medio,
        "Goal Keeping Skills": 0.2,
        "Response": medio,
        "Explosive Power": 0.6,
        "Dribble Speed": 0.6,
        "Top Speed": bajo,
        "Body Balance": medio,
        "Stamina": bajo,
        "Kicking Power": 0.6,
        "Jump": medio,
        "Tenacity": medio,
        "Teamwork": alto,
    },
    "CB": {
        "Attack": 0.2,
        "Defence": alto,
        "Header Accuracy": alto,
        "Dribble Accuracy": nulo,
        "Short Pass Accuracy": 0.6,
        "Short Pass Speed": 0.5,
        "Long Pass Accuracy": bajo,
        "Long Pass Speed": 0.6,
        "Shot Accuracy": nulo,
        "Place Kicking": 0.2,
        "Swerve": nulo,
        "Ball Controll": 0.5,
        "Goal Keeping Skills": nulo,
        "Response": bajo,
        "Explosive Power": 0.6,
        "Dribble Speed": 0.2,
        "Top Speed": 0.5,
        "Body Balance": alto,
        "Stamina": bajo,
        "Kicking Power": 0.4,
        "Jump": alto,
        "Tenacity": alto,
        "Teamwork": alto,
    },
    "LB": {
        "Attack": 0.6,
        "Defence": bajo,
        "Header Accuracy": 0.5,
        "Dribble Accuracy": bajo,
        "Short Pass Accuracy": bajo,
        "Short Pass Speed": 0.6,
        "Long Pass Accuracy": bajo,
        "Long Pass Speed": 0.6,
        "Shot Accuracy": nulo,
        "Place Kicking": nulo,
        "Swerve": 0.4,
        "Ball Controll": bajo,
        "Goal Keeping Skills": nulo,
        "Response": bajo,
        "Explosive Power": bajo,
        "Dribble Speed": bajo,
        "Top Speed": medio,
        "Body Balance": bajo,
        "Stamina": medio,
        "Kicking Power": 0.6,
        "Jump": 0.6,
        "Tenacity": bajo,
        "Teamwork": medio,
    },
    "RB": {
        "Attack": 0.6,
        "Defence": bajo,
        "Header Accuracy": 0.5,
        "Dribble Accuracy": bajo,
        "Short Pass Accuracy": bajo,
        "Short Pass Speed": 0.6,
        "Long Pass Accuracy": bajo,
        "Long Pass Speed": 0.6,
        "Shot Accuracy": nulo,
        "Place Kicking": nulo,
        "Swerve": 0.4,
        "Ball Controll": bajo,
        "Goal Keeping Skills": nulo,
        "Response": bajo,
        "Explosive Power": bajo,
        "Dribble Speed": bajo,
        "Top Speed": medio,
        "Body Balance": bajo,
        "Stamina": medio,
        "Kicking Power": 0.6,
        "Jump": 0.6,
        "Tenacity": bajo,
        "Teamwork": medio,
    },
    "DMF": {
        "Attack": 0.5,
        "Defence": medio,
        "Header Accuracy": 0.6,
        "Dribble Accuracy": 0.6,
        "Short Pass Accuracy": medio,
        "Short Pass Speed": bajo,
        "Long Pass Accuracy": bajo,
        "Long Pass Speed": bajo,
        "Shot Accuracy": nulo,
        "Place Kicking": nulo,
        "Swerve": 0.4,
        "Ball Controll": bajo,
        "Goal Keeping Skills": nulo,
        "Response": medio,
        "Explosive Power": 0.6,
        "Dribble Speed": 0.6,
        "Top Speed": 0.6,
        "Body Balance": medio,
        "Stamina": medio,
        "Kicking Power": 0.6,
        "Jump": bajo,
        "Tenacity": medio,
        "Teamwork": alto,
    },
    "CMF": {
        "Attack": bajo,
        "Defence": 0.6,
        "Header Accuracy": 0.5,
        "Dribble Accuracy": medio,
        "Short Pass Accuracy": medio,
        "Short Pass Speed": bajo,
        "Long Pass Accuracy": bajo,
        "Long Pass Speed": 0.6,
        "Shot Accuracy": 0.6,
        "Place Kicking": 0.5,
        "Swerve": 0.5,
        "Ball Controll": medio,
        "Goal Keeping Skills": nulo,
        "Response": medio,
        "Explosive Power": bajo,
        "Dribble Speed": bajo,
        "Top Speed": bajo,
        "Body Balance": bajo,
        "Stamina": medio,
        "Kicking Power": bajo,
        "Jump": 0.6,
        "Tenacity": medio,
        "Teamwork": alto,
    },
    "LMF": {
        "Attack": bajo,
        "Defence": 0.5,
        "Header Accuracy": 0.4,
        "Dribble Accuracy": bajo,
        "Short Pass Accuracy": bajo,
        "Short Pass Speed": bajo,
        "Long Pass Accuracy": bajo,
        "Long Pass Speed": 0.6,
        "Shot Accuracy": 0.5,
        "Place Kicking": 0.4,
        "Swerve": 0.5,
        "Ball Controll": medio,
        "Goal Keeping Skills": nulo,
        "Response": bajo,
        "Explosive Power": bajo,
        "Dribble Speed": bajo,
        "Top Speed": medio,
        "Body Balance": bajo,
        "Stamina": medio,
        "Kicking Power": 0.6,
        "Jump": 0.6,
        "Tenacity": bajo,
        "Teamwork": medio,
    },
    "RMF": {
        "Attack": bajo,
        "Defence": 0.5,
        "Header Accuracy": 0.4,
        "Dribble Accuracy": bajo,
        "Short Pass Accuracy": bajo,
        "Short Pass Speed": bajo,
        "Long Pass Accuracy": bajo,
        "Long Pass Speed": 0.6,
        "Shot Accuracy": 0.5,
        "Place Kicking": 0.4,
        "Swerve": 0.5,
        "Ball Controll": medio,
        "Goal Keeping Skills": nulo,
        "Response": bajo,
        "Explosive Power": bajo,
        "Dribble Speed": bajo,
        "Top Speed": medio,
        "Body Balance": bajo,
        "Stamina": medio,
        "Kicking Power": 0.6,
        "Jump": 0.6,
        "Tenacity": bajo,
        "Teamwork": medio,
    },
    "AMF": {
        "Attack": alto,
        "Defence": 0.4,
        "Header Accuracy": 0.6,
        "Dribble Accuracy": medio,
        "Short Pass Accuracy": medio,
        "Short Pass Speed": medio,
        "Long Pass Accuracy": medio,
        "Long Pass Speed": bajo,
        "Shot Accuracy": medio,
        "Place Kicking": bajo,
        "Swerve": bajo,
        "Ball Controll": alto,
        "Goal Keeping Skills": nulo,
        "Response": medio,
        "Explosive Power": bajo,
        "Dribble Speed": medio,
        "Top Speed": bajo,
        "Body Balance": bajo,
        "Stamina": bajo,
        "Kicking Power": bajo,
        "Jump": 0.6,
        "Tenacity": medio,
        "Teamwork": medio,
    },
    "LWF": {
        "Attack": medio,
        "Defence": 0.4,
        "Header Accuracy": 0.6,
        "Dribble Accuracy": medio,
        "Short Pass Accuracy": bajo,
        "Short Pass Speed": bajo,
        "Long Pass Accuracy": bajo,
        "Long Pass Speed": 0.6,
        "Shot Accuracy": medio,
        "Place Kicking": bajo,
        "Swerve": bajo,
        "Ball Controll": medio,
        "Goal Keeping Skills": nulo,
        "Response": alto,
        "Explosive Power": alto,
        "Dribble Speed": alto,
        "Top Speed": alto,
        "Body Balance": bajo,
        "Stamina": bajo,
        "Kicking Power": medio,
        "Jump": 0.6,
        "Tenacity": bajo,
        "Teamwork": bajo,
    },
    "RWF": {
        "Attack": medio,
        "Defence": 0.4,
        "Header Accuracy": 0.6,
        "Dribble Accuracy": medio,
        "Short Pass Accuracy": bajo,
        "Short Pass Speed": bajo,
        "Long Pass Accuracy": bajo,
        "Long Pass Speed": 0.6,
        "Shot Accuracy": medio,
        "Place Kicking": bajo,
        "Swerve": bajo,
        "Ball Controll": medio,
        "Goal Keeping Skills": nulo,
        "Response": alto,
        "Explosive Power": alto,
        "Dribble Speed": alto,
        "Top Speed": alto,
        "Body Balance": bajo,
        "Stamina": bajo,
        "Kicking Power": medio,
        "Jump": 0.6,
        "Tenacity": bajo,
        "Teamwork": bajo,
    },
    "SS": {
        "Attack": medio,
        "Defence": 0.4,
        "Header Accuracy": bajo,
        "Dribble Accuracy": medio,
        "Short Pass Accuracy": bajo,
        "Short Pass Speed": bajo,
        "Long Pass Accuracy": bajo,
        "Long Pass Speed": 0.6,
        "Shot Accuracy": alto,
        "Place Kicking": bajo,
        "Swerve": bajo,
        "Ball Controll": medio,
        "Goal Keeping Skills": nulo,
        "Response": alto,
        "Explosive Power": alto,
        "Dribble Speed": alto,
        "Top Speed": alto,
        "Body Balance": bajo,
        "Stamina": bajo,
        "Kicking Power": medio,
        "Jump": 0.6,
        "Tenacity": bajo,
        "Teamwork": bajo,
    },
    "CF": {
        "Attack": alto,
        "Defence": nulo,
        "Header Accuracy": alto,
        "Dribble Accuracy": medio,
        "Short Pass Accuracy": medio,
        "Short Pass Speed": medio,
        "Long Pass Accuracy": bajo,
        "Long Pass Speed": bajo,
        "Shot Accuracy": alto,
        "Place Kicking": medio,
        "Swerve": medio,
        "Ball Controll": alto,
        "Goal Keeping Skills": nulo,
        "Response": medio,
        "Explosive Power": medio,
        "Dribble Speed": medio,
        "Top Speed": medio,
        "Body Balance": alto,
        "Stamina": medio,
        "Kicking Power": alto,
        "Jump": alto,
        "Tenacity": alto,
        "Teamwork": alto,
    },
}

def generate_stats(position, rating):
    stats = {}

    for stat, weight in stats_weights[position].items():
        mean = 109 - (109 - rating) * 0.5
        std_dev = 10  # Desviación estándar de la distribución
        value = int(np.random.normal(mean * weight, std_dev) )
        value = max(value, 0)  # Asegurarse de que no sea negativo
        value = min(value, 99)  # Asegurarse de que esté entre 0 y 99
        stats[stat] = value
    # print()
    return stats